### ISSUE TITLE
undefined method `downcase' for nil:NilClass

### ISSUE THREAD

**Issue by jon2jay** [rstruber/dashing-haproxy#2]
Hello,
Not much activity here, but hopefully some body can point me in the right direction. Seeing this in the thin log: (no data being returned in the widget) I have confirmed the csv pulls and accessible:
here is the first row:

# pxname | svname | qcur | qmax | scur | smax | slim | stot | bin | bout | dreq | dresp | ereq | econ | eresp | wretr | wredis | status | weight | act | bck | chkfail | chkdown | lastchg | downtime | qlimit | pid | iid | sid | throttle | lbtot | tracked | type | rate | rate_lim | rate_max | check_status | check_code | check_duration | hrsp_1xx | hrsp_2xx | hrsp_3xx | hrsp_4xx | hrsp_5xx | hrsp_other | hanafail | req_rate | req_rate_max | req_tot | cli_abrt | srv_abrt | comp_in | comp_out | comp_byp | comp_rsp | lastsess | last_chk | last_agt | qtime | ctime | rtime | ttime |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

error in logs:

scheduler caught exception:
undefined method `downcase' for nil:NilClass
/usr/local/src/dashinga2/jobs/haproxy.rb:44:in `block (3 levels) in <top (required)>'
/usr/local/src/dashinga2/jobs/haproxy.rb:42:in `each'
/usr/local/src/dashinga2/jobs/haproxy.rb:42:in `block (2 levels) in <top (required)>'
/usr/local/src/dashinga2/jobs/haproxy.rb:41:in `each'
/usr/local/src/dashinga2/jobs/haproxy.rb:41:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.8/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/usr/local/rvm/gems/ruby-2.3.8/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/usr/local/rvm/gems/ruby-2.3.8/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'

**Comment by rstruber** [comment]
That looks like a "you tried to run a string function on a nil class" error. It's been a long time since I've touched or used this so it's possible that haproxy changed the data structure. I don't have anywhere to go get a dump in any reasonable amount of time.

The structure you are trying to loop through is here: https://github.com/rstruber/dashing-haproxy/blob/master/jobs/haproxy.rb#L41

Probably have to compare and see what's changed. If you have trouble with that, maybe share a csv with me and I could try to point you in a direction (no guarantee it's the right one).
